version: "3.9"

services:
  app:
    depends_on:
      - postgres
    image: app:latest
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_app
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  postgres:
    image: postgres:17.2
    container_name: postgres
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file:
      - .env
    volumes:
      - ./PG_DATA:/var/lib/postgresql/data
    networks:
      - internal
    ports: []
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
    driver: local
